dist: bionic
language: c
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - cppcheck
      - python3-venv
      - python3-pip
      - python3-distutils
      - python3-setuptools
      - python3-wheel
      - make
      - cmake
#services:
#  - docker
before_install:
    - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
    - sudo apt-get update -q
    - sudo apt-get install -y gcc-arm-embedded
    - pip3 install -U pip
    - pip3 install pynitrokey==0.3.2
    - pip3 install pipenv
script:
  - export CC=gcc-8
  - make travis
  - make -C tests/webcrypt-tests CI
